server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: dvs_prog
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
upload:
  server:
    folder: /home/msi/uploads/files

logging:
  level:
    sql: debug


